WindmistCity_Mart_MapScripts::
	.byte 0

WindmistCity_Mart_EventScript_Maniac::
	msgbox WindmistCity_Mart_Text_HaveYouHeardOfCircleThrow, MSGBOX_NPC
	end

WindmistCity_Mart_Text_HaveYouHeardOfCircleThrow:
	.string "Have you heard of the move\n"
	.string "Circle Throw?\p"
	.string "It forces the Pokémon it strikes\n"
	.string "to switch with a team member!$"

WindmistCity_Mart_EventScript_Hiker::
	msgbox WindmistCity_Mart_Text_NeedToMakeASwiftGetaway, MSGBOX_NPC
	end

WindmistCity_Mart_Text_NeedToMakeASwiftGetaway:
	.string "Need to make a swift getaway?\n"
	.string "Escape Ropes are for you!\p"
	.string "Shame they're so expensive…$"
