WindmistCity_House2_MapScripts::
	.byte 0

WindmistCity_House2_EventScript_OldMan::
	msgbox WindmistCity_House2_Text_NinasCookingIsRenowned, MSGBOX_NPC
	end

WindmistCity_House2_Text_NinasCookingIsRenowned:
	.string "Nina's cooking is renowned across\n"
	.string "the region.\p"
	.string "If she wasn't the Gym Leader, she\n"
	.string "could run a great restaurant!$"

WindmistCity_House2_EventScript_Lass::
	msgbox WindmistCity_House2_Text_IWannaTakeOnNina, MSGBOX_NPC
	end

WindmistCity_House2_Text_IWannaTakeOnNina:
	.string "I wanna take on Nina, but gramps\n"
	.string "says I shouldn't use Ice-types.$"
