#ifndef GUARD_CONSTANTS_LETTERS_H
#define GUARD_CONSTANTS_LETTERS_H

#define LETTER_MORGANAS_LETTER 0
#define NUM_LETTERS            (LETTER_MORGANAS_LETTER + 1)

#endif  // GUARD_CONSTANTS_LETTERS_H
