gText_Birch_Welcome::
	.string "Hello there!\p"
	.string "Welcome to the wonderful world of\n"
	.string "Pokémon!\p"
	.string "The name's Redwood!\n"
	.string "I'm a Pokémon Professor.\p"
	.string "I study our fascinating world, and\n"
	.string "the creatures that inhabit it.\p"
	.string "I am also an archaeologist!\n"
	.string "Unravelling the past is my passion.\p$"

gText_Birch_Pokemon::
	.string "This is Kabuto, a Pokémon!{PAUSE 96}\p$"

gText_Birch_MainSpeech::
	.string "Pokémon are our friends, pets, and\n"
	.string "work partners!\p"
	.string "With today's technology, we can\n"
	.string "revive Kabuto from mere Fossils.\p"
	.string "Indeed, the tenacity of life is\n"
	.string "something to behold.\p$"

gText_Birch_AndYouAre::
	.string "But enough about me!$"

gText_Birch_BoyOrGirl::
	.string "Tell me, are you a boy, or a girl?$"

gText_Birch_WhatsYourName::
	.string "I see!\n"
	.string "And your name is?$"

gText_Birch_SoItsPlayer::
	.string "Ah!\n"
	.string "Your name is {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Wonderful, {PLAYER}!\p"
	.string "You say you live in Celanto Town?\n"
	.string "I'll be headed there myself, soon.\p"
	.string "How exciting!\p$"

gText_Birch_AreYouReady::
	.string "Now!\n"
	.string "This adventure of yours…\p"
	.string "It will surely be one for the\n"
	.string "history books!\p"
	.string "Make it count, okay?\p$"
