gText_ObtainedTheItem:: @ 8272A78
	.string "{COLOR DARK_GREY}Obtained the {STR_VAR_2}!$"

gText_TheBagIsFull:: @ 8272A89
	.string "{COLOR DARK_GREY}The Bag is full…$"

gText_PutItemInPocket:: @ 8272A9A
	.string "{COLOR DARK_GREY}{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} Pocket.$"

gText_PlayerFoundOneItem:: @ 8272ABF
	.string "{COLOR DARK_GREY}{PLAYER} found one {STR_VAR_2}!$"

gText_TooBadBagIsFull:: @ 8272AD0
	.string "{COLOR DARK_GREY}Too bad!\n"
	.string "The Bag is full…$"

gText_PlayerPutItemInBag:: @ 8272AEA
	.string "{COLOR DARK_GREY}{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the Bag.$"

gText_ObtainedTheDecor:: @ 8272B09
	.string "{COLOR DARK_GREY}Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother:: @ 8272B1A
	.string "{COLOR DARK_GREY}Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC:: @ 8272B48
	.string "{COLOR DARK_GREY}The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"
