gText_WouldYouLikeToRestYourPkmn::
    .string "Welcome! Would you like to rest\n"
	.string "your Pokémon to perfect health?$"

gText_IllTakeYourPkmn::
    .string "Okay, I'll take your Pokémon\n"
    .string "for a few seconds.$"

gText_RestoredPkmnToFullHealth::
    .string "Thanks for waiting!\n"
    .string "We hope to see you again!$"

gText_WeHopeToSeeYouAgain::
    .string "We hope to see you again!$"

gText_PokerusExplanation::
	.string "Your Pokémon may be infected with\n"
	.string "PokéRus.\p"
	.string "PokéRus are microscopic life-\n"
	.string "forms that attach to Pokémon.\p"
	.string "Infected Pokémon are said to\n"
	.string "grow exceptionally well.$"
