CelantoTown_House1_MapScripts::
	.byte 0

CelantoTown_House1_EventScript_LittleGirl::
	msgbox CelantoTown_House1_Text_IHateMyBigBrother, MSGBOX_NPC
	end

CelantoTown_House1_Text_IHateMyBigBrother:
	.string "I hate my big brother…\p"
	.string "I got a scratch on my leg once in\n"
	.string "Celanto Path.\p"
	.string "Now he stops anyone from leaving\n"
	.string "the town without a Pokémon!$"

CelantoTown_House1_EventScript_OldWoman::
	msgbox CelantoTown_House1_Text_HaveYouSeenTheRock, MSGBOX_NPC
	end

CelantoTown_House1_Text_HaveYouSeenTheRock:
	.string "Have you seen the rock by the\n"
	.string "Totem Poles in the Reliquia Ruins?\p"
	.string "It has a message carved in it, but\n"
	.string "few know the language to translate.$"
