NestpineTown_House3_MapScripts::
	.byte 0

NestpineTown_House3_EventScript_Lass::
	msgbox NestpineTown_House3_Text_MyBoyfriendLivesInAerousCity, MSGBOX_NPC
	end

NestpineTown_House3_Text_MyBoyfriendLivesInAerousCity:
	.string "My boyfriend lives in Aerous City.\p"
	.string "It's tough, maintaining a long-\n"
	.string "distance relationship.\p"
	.string "We keep in touch via mail!\p"
	.string "Personalized messages are a great\n"
	.string "way to feel close.$"
