// TODO: Remove duplicate definition labels
// TODO: Add Regal Stone item

EventScript_ItemPotion::
Route102_EventScript_ItemPotion::
Route104_EventScript_ItemPotion::
Route109_EventScript_ItemPotion::
Route116_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

EventScript_ItemSuperPotion::
Route115_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

EventScript_ItemHyperPotion::
Route120_EventScript_ItemHyperPotion::
Route119_EventScript_ItemHyperPotion2::
Route119_EventScript_ItemHyperPotion::
Route118_EventScript_ItemHyperPotion::
Route113_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

EventScript_ItemMaxPotion::
MtPyre_Exterior_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

EventScript_ItemFullRestore::
MagmaHideout_2F_2R_EventScript_ItemFullRestore::
VictoryRoad_B1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

EventScript_ItemRevive::
Route117_EventScript_ItemRevive::
Route120_EventScript_ItemRevive::
Route121_EventScript_ItemRevive::
AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

EventScript_ItemMaxRevive::
MagmaHideout_4F_EventScript_MaxRevive::
SafariZone_Southwest_EventScript_ItemMaxRevive::
PetalburgCity_EventScript_ItemMaxRevive::
Route133_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

EventScript_ItemRareCandy::
Route110_EventScript_ItemRareCandy::
Route114_EventScript_ItemRareCandy::
Route119_EventScript_ItemRareCandy::
Route127_EventScript_ItemRareCandy::
Route132_EventScript_ItemRareCandy::
GraniteCave_B2F_EventScript_ItemRareCandy::
ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
MagmaHideout_1F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

EventScript_ItemTM37::
Route111_EventScript_ItemTM37::
	finditem ITEM_TM37
	end

EventScript_ItemShinyStone::
	finditem ITEM_SHINY_STONE
	end

EventScript_ItemEscapeRope::
GraniteCave_1F_EventScript_ItemEscapeRope::
NewMauville_Inside_EventScript_ItemEscapeRope::
AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

EventScript_ItemMaxEther::
RusturfTunnel_EventScript_ItemMaxEther::
Route113_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

EventScript_ItemEther::
PetalburgWoods_EventScript_ItemEther::
PetalburgCity_EventScript_ItemEther::
Route116_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

EventScript_ItemElixir::
Route123_EventScript_ItemElixir::
Route119_EventScript_ItemElixir2::
Route119_EventScript_ItemElixir::
Route111_EventScript_ItemElixir::
Route110_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

Route112_EventScript_ItemNugget::
Route120_EventScript_ItemNugget::
SafariZone_Northeast_EventScript_ItemNugget::
AquaHideout_B1F_EventScript_ItemNugget::
Route119_EventScript_ItemNugget::
MagmaHideout_3F_1R_EventScript_ItemNugget::
EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

EventScript_ItemAssaultVest::
	finditem ITEM_ASSAULT_VEST
	end

EventScript_ItemCleanseTag::
	finditem ITEM_CLEANSE_TAG
	end

EventScript_ItemTM10::
	finditem ITEM_TM10
	end

EventScript_ItemTM39::
	finditem ITEM_TM39
	end

EventScript_ItemEviolite::
	finditem ITEM_EVIOLITE
	end

EventScript_ItemTM12::
	finditem ITEM_TM12
	end

EventScript_ItemTM20::
	finditem ITEM_TM20
	end

MtPyre_3F_EventScript_ItemSuperRepel::
Route119_EventScript_ItemSuperRepel::
Route113_EventScript_ItemSuperRepel::
EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

EventScript_ItemPokeBall::
GraniteCave_B1F_EventScript_ItemPokeBall::
RusturfTunnel_EventScript_ItemPokeBall::
Route104_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

EventScript_ItemSharpedonite::
	finditem ITEM_SHARPEDONITE
	end

EventScript_ItemTM21::
	finditem ITEM_TM21
	end

EventScript_ItemJawFossil::
	finditem ITEM_JAW_FOSSIL
	end

EventScript_ItemFireStone::
FieryPath_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

EventScript_ItemTM06::
FieryPath_EventScript_ItemTM06::
	finditem ITEM_TM06
	end

EventScript_ItemSilkScarf::
	finditem ITEM_SILK_SCARF
	end

EventScript_ItemRegalStone::
	finditem ITEM_SUN_STONE
	end

EventScript_ItemRootFossil::
	finditem ITEM_ROOT_FOSSIL
	end

EventScript_ItemFullHeal::
VictoryRoad_B2F_EventScript_ItemFullHeal::
NewMauville_Inside_EventScript_ItemFullHeal::
MeteorFalls_1F_1R_EventScript_ItemFullHeal::
Route120_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

EventScript_ItemTM33::
	finditem ITEM_TM33
	end

EventScript_ItemIron::
Route115_EventScript_ItemIron::
Route105_EventScript_ItemIron::
	finditem ITEM_IRON
	end

EventScript_ItemNeverMeltIce:: 
ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

EventScript_ItemTM07::
ShoalCave_LowTideIceRoom_EventScript_ItemTM07::
	finditem ITEM_TM07
	end

EventScript_ItemItemfinder::
	finditem ITEM_ITEMFINDER
	end

EventScript_ItemPPUp::
VictoryRoad_1F_EventScript_ItemPPUp::
MeteorFalls_1F_1R_EventScript_ItemPPUP::
Route123_EventScript_ItemPPUp::
Route115_EventScript_ItemPPUp::
Route109_EventScript_ItemPPUp::
Route104_EventScript_ItemPPUp::
Route103_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

EventScript_ItemXSpAtk::
Route116_EventScript_ItemXSpecial::
	finditem ITEM_X_SP_ATK
	end

EventScript_ItemKingsRock::
	finditem ITEM_KINGS_ROCK
	end

EventScript_ItemMiracleSeed::
	finditem ITEM_MIRACLE_SEED
	end

EventScript_ItemDawnStone::
	finditem ITEM_DAWN_STONE
	end

EventScript_ItemTM18::
AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18::
	finditem ITEM_TM18
	end

EventScript_ItemTM16::
	finditem ITEM_TM16
	end

EventScript_ItemSunStone::
	finditem ITEM_SUN_STONE
	end

EventScript_ItemGlalitite::
	finditem ITEM_GLALITITE
	end

EventScript_ItemSailFossil::
	finditem ITEM_SAIL_FOSSIL
	end

EventScript_ItemTM50::
	finditem ITEM_TM50
	end

EventScript_ItemRockyHelmet::
	finditem ITEM_ROCKY_HELMET
	end

EventScript_ItemStarPiece::
Route134_EventScript_ItemStarPiece::
Route133_EventScript_ItemStarPiece::
Route108_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

EventScript_ItemTM31::
	finditem ITEM_TM31
	end

EventScript_ItemWaterStone::
AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end

EventScript_ItemTM40::
	finditem ITEM_TM40
	end

EventScript_ItemLeafStone::
Route119_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

EventScript_ItemAbilityPill::
	finditem ITEM_ABILITY_CAPSULE
	end

EventScript_ItemTM30::
	finditem ITEM_TM30
	end

EventScript_ItemGyaradosite::
	finditem ITEM_GYARADOSITE
	end

EventScript_ItemZinc::
Route127_EventScript_ItemZinc::
Route121_EventScript_ItemZinc::
Route119_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

EventScript_ItemHelixFossil::
	finditem ITEM_HELIX_FOSSIL
	end

EventScript_ItemAltarianite::
	finditem ITEM_ALTARIANITE
	end

EventScript_ItemTM28::
	finditem ITEM_TM28
	end

EventScript_ItemOldAmber::
	finditem ITEM_OLD_AMBER
	end

Route103_EventScript_ItemGuardSpec:: @ 8290CE5
	finditem ITEM_GUARD_SPEC
	end

Route104_EventScript_ItemXAccuracy:: @ 8290D19
	finditem ITEM_X_ACCURACY
	end

Route106_EventScript_ItemProtein:: @ 8290D40
	finditem ITEM_PROTEIN
	end

Route110_EventScript_ItemDireHit:: @ 8290D81
	finditem ITEM_DIRE_HIT
	end

Route111_EventScript_ItemStardust:: @ 8290DA8
	finditem ITEM_STARDUST
	end

Route111_EventScript_ItemHPUp:: @ 8290DB5
	finditem ITEM_HP_UP
	end

Route114_EventScript_ItemProtein:: @ 8290E10
	finditem ITEM_PROTEIN
	end

Route114_EventScript_ItemEnergyPowder:: @ 8290E1D
	finditem ITEM_ENERGY_POWDER
	end

Route115_EventScript_ItemTM01:: @ 8290E37
	finditem ITEM_TM01
	end

Route115_EventScript_ItemGreatBall:: @ 8290E51
	finditem ITEM_GREAT_BALL
	end

Route115_EventScript_ItemHealPowder:: @ 8290E5E
	finditem ITEM_HEAL_POWDER
	end

Route116_EventScript_ItemRepel:: @ 8290E92
	finditem ITEM_REPEL
	end

Route116_EventScript_ItemHPUp:: @ 8290E9F
	finditem ITEM_HP_UP
	end

Route117_EventScript_ItemGreatBall:: @ 8290EB9
	finditem ITEM_GREAT_BALL
	end

Route120_EventScript_ItemNestBall:: @ 8290F6F
	finditem ITEM_NEST_BALL
	end

Route121_EventScript_ItemCarbos:: @ 8290F89
	finditem ITEM_CARBOS
	end

Route123_EventScript_ItemCalcium:: @ 8290FB0
	finditem ITEM_CALCIUM
	end

Route123_EventScript_ItemUltraBall:: @ 8290FBD
	finditem ITEM_ULTRA_BALL
	end

Route123_EventScript_ItemRevivalHerb:: @ 8290FE4
	finditem ITEM_REVIVAL_HERB
	end

Route124_EventScript_ItemRedShard:: @ 8290FF1
	finditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard:: @ 8290FFE
	finditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard:: @ 829100B
	finditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl:: @ 8291018
	finditem ITEM_BIG_PEARL
	end

Route126_EventScript_ItemGreenShard:: @ 8291025
	finditem ITEM_GREEN_SHARD
	end

Route127_EventScript_ItemCarbos:: @ 829103F
	finditem ITEM_CARBOS
	end

Route132_EventScript_ItemProtein:: @ 8291066
	finditem ITEM_PROTEIN
	end

Route133_EventScript_ItemBigPearl:: @ 8291073
	finditem ITEM_BIG_PEARL
	end

Route134_EventScript_ItemCarbos:: @ 829109A
	finditem ITEM_CARBOS
	end

MauvilleCity_EventScript_ItemXSpeed:: @ 82910CE
	finditem ITEM_X_SPEED
	end

RustboroCity_EventScript_ItemXDefend:: @ 82910DB
	finditem ITEM_X_DEFENSE
	end

LilycoveCity_EventScript_ItemMaxRepel:: @ 82910E8
	finditem ITEM_MAX_REPEL
	end

MossdeepCity_EventScript_ItemNetBall:: @ 82910F5
	finditem ITEM_NET_BALL
	end

PetalburgWoods_EventScript_ItemXAttack:: @ 8291102
	finditem ITEM_X_ATTACK
	end

PetalburgWoods_EventScript_ItemGreatBall:: @ 829110F
	finditem ITEM_GREAT_BALL
	end

PetalburgWoods_EventScript_ItemParalyzeHeal:: @ 8291129
	finditem ITEM_PARALYZE_HEAL
	end

GraniteCave_B2F_EventScript_ItemRepel:: @ 829116A
	finditem ITEM_REPEL
	end

JaggedPass_EventScript_ItemBurnHeal:: @ 8291184
	finditem ITEM_BURN_HEAL
	end

MeteorFalls_1F_1R_EventScript_ItemTM23:: @ 82911AB
	finditem ITEM_TM23
	end

MeteorFalls_B1F_2R_EventScript_ItemTM02:: @ 82911DF
	finditem ITEM_TM02
	end

NewMauville_Inside_EventScript_ItemUltraBall:: @ 82911EC
	finditem ITEM_ULTRA_BALL
	end

NewMauville_Inside_EventScript_ItemThunderStone:: @ 8291206
	finditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal:: @ 8291220
	finditem ITEM_PARALYZE_HEAL
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail:: @ 829122D
	finditem ITEM_HARBOR_MAIL
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall:: @ 8291247
	finditem ITEM_DIVE_BALL
	end

AbandonedShip_Room_B1F_EventScript_ItemTM13:: @ 8291254
	finditem ITEM_TM13
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey:: @ 829126E
	finditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall:: @ 829127B
	finditem ITEM_LUXURY_BALL
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner:: @ 8291288
	finditem ITEM_SCANNER
	end

ScorchedSlab_EventScript_ItemTM11:: @ 82912AF
	finditem ITEM_TM11
	end

SafariZone_Northwest_EventScript_ItemTM22:: @ 82912BC
	finditem ITEM_TM22
	end

SafariZone_North_EventScript_ItemCalcium:: @ 82912C9
	finditem ITEM_CALCIUM
	end

SafariZone_Southeast_EventScript_ItemBigPearl:: @ 82912F0
	finditem ITEM_BIG_PEARL
	end

MtPyre_2F_EventScript_ItemUltraBall:: @ 82912FD
	finditem ITEM_ULTRA_BALL
	end

MtPyre_4F_EventScript_ItemSeaIncense:: @ 8291317
	finditem ITEM_SEA_INCENSE
	end

MtPyre_5F_EventScript_ItemLaxIncense:: @ 8291324
	finditem ITEM_LAX_INCENSE
	end

MtPyre_6F_EventScript_ItemTM30:: @ 8291331
	finditem ITEM_TM30
	end

MtPyre_Exterior_EventScript_ItemTM48:: @ 829134B
	finditem ITEM_TM48
	end

AquaHideout_B1F_EventScript_ItemMasterBall:: @ 8291358
	finditem ITEM_MASTER_BALL
	end

AquaHideout_B1F_EventScript_ItemMaxElixir:: @ 8291372
	finditem ITEM_MAX_ELIXIR
	end

AquaHideout_B2F_EventScript_ItemNestBall:: @ 829137F
	finditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall:: @ 829138C
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemMaxElixir:: @ 82913A6
	finditem ITEM_MAX_ELIXIR
	end

Route119_EventScript_ItemNestBall:: @ 82913B3
	finditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl:: @ 82913C0
	finditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal:: @ 82913DA
	finditem ITEM_ICE_HEAL
	end

SeafloorCavern_Room9_EventScript_ItemTM26:: @ 8291401
	finditem ITEM_TM26
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail:: @ 829140E
	finditem ITEM_ORANGE_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail:: @ 829141B
	finditem ITEM_HARBOR_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail:: @ 8291428
	finditem ITEM_WAVE_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail:: @ 8291435
	finditem ITEM_SHADOW_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail:: @ 8291442
	finditem ITEM_WOOD_MAIL
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail:: @ 829144F
	finditem ITEM_MECH_MAIL
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail:: @ 829145C
	finditem ITEM_GLITTER_MAIL
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail:: @ 8291469
	finditem ITEM_TROPIC_MAIL
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail:: @ 8291476
	finditem ITEM_BEAD_MAIL
	end

VictoryRoad_1F_EventScript_ItemMaxElixir:: @ 8291483
	finditem ITEM_MAX_ELIXIR
	end

VictoryRoad_B1F_EventScript_ItemTM29:: @ 829149D
	finditem ITEM_TM29
	end

ArtisanCave_B1F_EventScript_ItemHPUp:: @ 82914C4
	finditem ITEM_HP_UP
	end

ArtisanCave_1F_EventScript_ItemCarbos:: @ 82914D1
	finditem ITEM_CARBOS
	end

MagmaHideout_2F_2R_EventScript_MaxElixir:: @ 82914EB
	finditem ITEM_MAX_ELIXIR
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax:: @ 8291512
	finditem ITEM_PP_MAX
	end
