SabuloIsland_Mart_MapScripts::
	.byte 0

SabuloIsland_Mart_EventScript_Maniac::
	msgbox SabuloIsland_Mart_Text_MegaStonesAreTrickyToFind, MSGBOX_NPC
	end

SabuloIsland_Mart_Text_MegaStonesAreTrickyToFind:
	.string "Mega Stones are tricky to find.\p"
	.string "But, there's something thrilling\n"
	.string "about when you finally do!\p"
	.string "Ooh! I get chills just thinking\n"
	.string "about it!$"
